use_frameworks!

platform :ios, '9.0'

target 'Warpgate_Example' do
  pod 'Warpgate', :path => '../'

  target 'Warpgate_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
